### ISSUE TITLE
Component Library 

### ISSUE THREAD

**Issue by VanshSh** [nowandme/frontend-developer-task#1]
Is it allowed to use Component Library for creating components in React such as Material UI,Ant Design etc.

**Comment by niteshkumarniranjan** [comment]
Though we don't necessarily discourage the use of a component library, we prefer using unstyled primitive such as
- https://www.radix-ui.com/
- https://headlessui.dev/ 
- https://react-spectrum.adobe.com/react-aria/

**Comment by niteshkumarniranjan** [comment]
As a developer, it's up to you to use whatever you see fit for the task.
